import jsPDF from "jspdf";

/* ═══ Dark neutral premium palette ═══ */
const BG = "#09090B";
const BG_CARD = "#141418";
const ACCENT = "#C8A84E";
const POSITIVE = "#3ECF8E";
const NEGATIVE = "#F75B5B";
const TEXT_PRIMARY = "#EDEDEF";
const TEXT_SECONDARY = "#A1A1AA";
const TEXT_TERTIARY = "#71717A";
const BORDER = "#232329";

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;

/* Agent name → color (matches AgentCard) */
const AGENT_COLORS: Record<string, string> = {
  strategist: "#A8A29E", strategy: "#A8A29E", base: "#A8A29E",
  finance: "#7DD3FC", financial: "#7DD3FC", unit: "#7DD3FC",
  operator: "#FCD34D", operations: "#FCD34D", execution: "#FCD34D",
  market: "#6EE7B7", demand: "#6EE7B7",
  risk: "#FCA5A5", regulatory: "#FCA5A5", regime: "#FCA5A5",
  innovator: "#F09A72", innovation: "#F09A72", intervention: "#F09A72",
  devil: "#FDBA74", adversary: "#FDBA74", competitive: "#FDBA74",
  global: "#5EEAD4",
  human: "#F9A8D4", customer: "#F9A8D4",
  futurist: "#A5B4FC", decision: "#A5B4FC",
};

function getAgentColor(name: string, fallback?: string): string {
  const lower = (name || "").toLowerCase();
  for (const [key, color] of Object.entries(AGENT_COLORS)) {
    if (lower.includes(key)) return color;
  }
  return fallback || TEXT_SECONDARY;
}

function hexToRgb(hex: string): [number, number, number] {
  const clean = hex.replace("#", "").slice(0, 6);
  const r = parseInt(clean.slice(0, 2), 16);
  const g = parseInt(clean.slice(2, 4), 16);
  const b = parseInt(clean.slice(4, 6), 16);
  return [r, g, b];
}

function setColor(doc: jsPDF, hex: string) {
  doc.setTextColor(...hexToRgb(hex));
}

function drawBg(doc: jsPDF) {
  doc.setFillColor(...hexToRgb(BG));
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");
}

function drawCard(doc: jsPDF, x: number, y: number, w: number, h: number) {
  doc.setFillColor(...hexToRgb(BG_CARD));
  doc.roundedRect(x, y, w, h, 2, 2, "F");
  doc.setDrawColor(...hexToRgb(BORDER));
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, "S");
}

function sectionLabel(doc: jsPDF, text: string, y: number): number {
  setColor(doc, TEXT_TERTIARY);
  doc.setFontSize(8);
  doc.setFont("courier", "normal");
  doc.text(text.toUpperCase(), MARGIN, y);
  return y + 8;
}

function footer(doc: jsPDF, page: number, total: number) {
  setColor(doc, TEXT_TERTIARY);
  doc.setFontSize(7);
  doc.setFont("courier", "normal");
  doc.text("Generated by Signux AI — signux-ai.vercel.app", MARGIN, PAGE_H - 10);
  doc.text(`${page}/${total}`, PAGE_W - MARGIN, PAGE_H - 10, { align: "right" });
}

function wrapText(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text || "", maxWidth);
}

export function exportSimulationPdf(data: {
  scenario: string;
  rounds: any[];
  verdict: any;
  evolution: any[];
}) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const { scenario, rounds, verdict, evolution } = data;
  const totalPages = 6;
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const totalInteractions = (rounds || []).reduce((sum: number, r: any) => sum + (r.agents?.length || 0), 0);

  // ═══ PAGE 1: COVER ═══
  drawBg(doc);

  // Accent line
  doc.setFillColor(...hexToRgb(ACCENT));
  doc.rect(MARGIN, 60, 30, 1, "F");

  // Logo
  setColor(doc, ACCENT);
  doc.setFontSize(14);
  doc.setFont("courier", "normal");
  doc.text("SIGNUX AI", MARGIN, 72);

  // Title
  setColor(doc, TEXT_PRIMARY);
  doc.setFontSize(28);
  doc.setFont("helvetica", "normal");
  doc.text("Simulation Report", MARGIN, 95);

  // Scenario card
  drawCard(doc, MARGIN, 115, CONTENT_W, 40);
  setColor(doc, TEXT_TERTIARY);
  doc.setFontSize(8);
  doc.setFont("courier", "normal");
  doc.text("SCENARIO", MARGIN + 10, 124);
  setColor(doc, TEXT_PRIMARY);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const scenarioLines = wrapText(doc, scenario, CONTENT_W - 20);
  doc.text(scenarioLines.slice(0, 4), MARGIN + 10, 132);

  // Meta
  setColor(doc, TEXT_TERTIARY);
  doc.setFontSize(9);
  doc.setFont("courier", "normal");
  doc.text(dateStr, MARGIN, 175);
  doc.text(`${(rounds || []).length || 10} agents · ${(rounds || []).length || 10} rounds · ${totalInteractions || 100} interactions`, MARGIN, 182);

  footer(doc, 1, totalPages);

  // ═══ PAGE 2: EXECUTIVE SUMMARY ═══
  doc.addPage();
  drawBg(doc);
  let y = sectionLabel(doc, "Executive Summary", 25);

  if (verdict) {
    const isProceed = (verdict.proceedCount || 0) >= (verdict.stopCount || 0);

    // Vote result
    drawCard(doc, MARGIN, y, CONTENT_W, 32);

    // Vote count
    setColor(doc, isProceed ? POSITIVE : NEGATIVE);
    doc.setFontSize(28);
    doc.setFont("helvetica", "normal");
    doc.text(`${isProceed ? verdict.proceedCount : verdict.stopCount}`, MARGIN + 10, y + 16);
    setColor(doc, TEXT_TERTIARY);
    doc.setFontSize(18);
    doc.text("–", MARGIN + 24, y + 16);
    setColor(doc, isProceed ? NEGATIVE : POSITIVE);
    doc.setFontSize(28);
    doc.text(`${isProceed ? verdict.stopCount : verdict.proceedCount}`, MARGIN + 30, y + 16);

    setColor(doc, isProceed ? POSITIVE : NEGATIVE);
    doc.setFontSize(9);
    doc.setFont("courier", "normal");
    doc.text(isProceed ? "PROCEED" : "STOP", MARGIN + 10, y + 24);

    // Viability
    setColor(doc, TEXT_SECONDARY);
    doc.setFontSize(22);
    doc.setFont("helvetica", "normal");
    doc.text(`${verdict.viability || 0}/10`, MARGIN + 70, y + 16);
    setColor(doc, TEXT_TERTIARY);
    doc.setFontSize(8);
    doc.setFont("courier", "normal");
    doc.text("VIABILITY", MARGIN + 70, y + 24);

    // Confidence
    setColor(doc, TEXT_TERTIARY);
    doc.setFontSize(18);
    doc.setFont("helvetica", "normal");
    doc.text(`${verdict.avgConfidence || 0}`, MARGIN + 110, y + 16);
    doc.setFontSize(8);
    doc.setFont("courier", "normal");
    doc.text("AVG CONF", MARGIN + 110, y + 24);

    // ROI
    if (verdict.estimatedROI && verdict.estimatedROI !== "N/A") {
      const roiColor = (typeof verdict.estimatedROI === "string" && verdict.estimatedROI.startsWith("-")) ? NEGATIVE : POSITIVE;
      setColor(doc, roiColor);
      doc.setFontSize(18);
      doc.setFont("helvetica", "normal");
      doc.text(verdict.estimatedROI, MARGIN + 140, y + 16);
      setColor(doc, TEXT_TERTIARY);
      doc.setFontSize(8);
      doc.setFont("courier", "normal");
      doc.text("EST. ROI", MARGIN + 140, y + 24);
    }
    y += 38;

    // Verdict text
    if (verdict.verdict) {
      setColor(doc, TEXT_PRIMARY);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const verdictLines = wrapText(doc, typeof verdict.verdict === "string" ? verdict.verdict : String(verdict.verdict), CONTENT_W);
      doc.text(verdictLines.slice(0, 5), MARGIN, y);
      y += verdictLines.slice(0, 5).length * 5 + 6;
    }

    // Key Risk + Key Opportunity
    if (verdict.keyRisk || verdict.keyOpportunity) {
      const halfW = (CONTENT_W - 6) / 2;
      if (verdict.keyRisk) {
        drawCard(doc, MARGIN, y, halfW, 28);
        setColor(doc, NEGATIVE);
        doc.setFontSize(8);
        doc.setFont("courier", "normal");
        doc.text("KEY RISK", MARGIN + 8, y + 8);
        setColor(doc, TEXT_SECONDARY);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        const riskLines = wrapText(doc, typeof verdict.keyRisk === "string" ? verdict.keyRisk : "", halfW - 16);
        doc.text(riskLines.slice(0, 3), MARGIN + 8, y + 14);
      }
      if (verdict.keyOpportunity) {
        const ox = MARGIN + halfW + 6;
        drawCard(doc, ox, y, halfW, 28);
        setColor(doc, POSITIVE);
        doc.setFontSize(8);
        doc.setFont("courier", "normal");
        doc.text("KEY OPPORTUNITY", ox + 8, y + 8);
        setColor(doc, TEXT_SECONDARY);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        const oppLines = wrapText(doc, typeof verdict.keyOpportunity === "string" ? verdict.keyOpportunity : "", halfW - 16);
        doc.text(oppLines.slice(0, 3), ox + 8, y + 14);
      }
      y += 34;
    }

    // Individual votes
    if (verdict.votes && verdict.votes.length > 0) {
      y = sectionLabel(doc, "Individual Votes", y);
      verdict.votes.forEach((v: any, i: number) => {
        const vColor = v.vote === "PROCEED" ? POSITIVE : NEGATIVE;
        const agentName = typeof v.agent === "string" ? v.agent.split(" ").pop() || "Agent" : "Agent";
        const col = i % 3;
        const row = Math.floor(i / 3);
        const cx = MARGIN + col * (CONTENT_W / 3);
        const cy = y + row * 10;
        setColor(doc, getAgentColor(agentName));
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.text(agentName, cx, cy);
        setColor(doc, vColor);
        doc.setFont("courier", "normal");
        doc.text(v.vote, cx + 35, cy);
      });
    }
  }

  footer(doc, 2, totalPages);

  // ═══ PAGE 3: AGENT OVERVIEW ═══
  doc.addPage();
  drawBg(doc);
  y = sectionLabel(doc, "Agent Overview — Final Positions", 25);

  const lastRound = rounds?.[rounds.length - 1];
  const agents = lastRound?.agents || [];

  agents.forEach((agent: any, i: number) => {
    if (y > PAGE_H - 30) {
      footer(doc, 3, totalPages);
      doc.addPage();
      drawBg(doc);
      y = 25;
    }
    const cardH = 22;
    drawCard(doc, MARGIN, y, CONTENT_W, cardH);

    // Name in agent color
    const nameColor = getAgentColor(agent.name, agent.color);
    setColor(doc, nameColor);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(agent.name || `Agent ${i + 1}`, MARGIN + 8, y + 7);

    // Sentiment dot + confidence
    const sentColor = agent.sentiment === "confident" || agent.sentiment === "optimistic" || agent.sentiment === "excited"
      ? POSITIVE : agent.sentiment === "worried" || agent.sentiment === "concerned" ? NEGATIVE : TEXT_TERTIARY;
    doc.setFillColor(...hexToRgb(sentColor));
    doc.circle(MARGIN + 8, y + 13, 1.2, "F");

    setColor(doc, TEXT_SECONDARY);
    doc.setFontSize(9);
    doc.setFont("courier", "normal");
    doc.text(`${agent.confidence || 0}/10`, MARGIN + 12, y + 14);

    // Text preview
    if (agent.text) {
      setColor(doc, TEXT_SECONDARY);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      const preview = wrapText(doc, typeof agent.text === "string" ? agent.text : String(agent.text), CONTENT_W - 16);
      doc.text(preview.slice(0, 1), MARGIN + 8, y + 20);
    }

    y += cardH + 3;
  });

  footer(doc, 3, totalPages);

  // ═══ PAGE 4: EVOLUTION ═══
  doc.addPage();
  drawBg(doc);
  y = sectionLabel(doc, "Agent Evolution — 10 Rounds", 25);

  if (evolution && evolution.length > 0) {
    // Header row
    setColor(doc, TEXT_TERTIARY);
    doc.setFontSize(7);
    doc.setFont("courier", "normal");
    for (let r = 1; r <= 10; r++) {
      doc.text(`R${r}`, MARGIN + 52 + (r - 1) * 12, y);
    }
    y += 5;

    evolution.forEach((agent: any) => {
      if (y > PAGE_H - 30) {
        footer(doc, 4, totalPages);
        doc.addPage();
        drawBg(doc);
        y = 25;
      }

      // Agent name
      const nameColor = getAgentColor(agent.name, agent.color);
      setColor(doc, nameColor);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      const shortName = (agent.name || "Agent").replace("The ", "");
      doc.text(shortName.length > 12 ? shortName.slice(0, 12) + "..." : shortName, MARGIN, y + 4);

      // Round dots
      const arc = agent.arc || [];
      arc.forEach((r: any, ri: number) => {
        const dx = MARGIN + 55 + ri * 12;
        const sentCol = r.sentiment === "confident" || r.sentiment === "optimistic" || r.sentiment === "excited" || r.sentiment === "convinced"
          ? POSITIVE : r.sentiment === "worried" || r.sentiment === "concerned" ? NEGATIVE
          : r.sentiment === "skeptical" || r.sentiment === "cautious" ? "#F59E0B" : TEXT_TERTIARY;

        doc.setFillColor(...hexToRgb(r.changedMind ? ACCENT : sentCol));
        doc.circle(dx, y + 3, r.changedMind ? 1.8 : 1.2, "F");
      });

      // Final confidence + delta
      const firstConf = arc[0]?.confidence || 5;
      const lastConf = arc[arc.length - 1]?.confidence || 5;
      const delta = lastConf - firstConf;
      setColor(doc, TEXT_SECONDARY);
      doc.setFontSize(9);
      doc.setFont("courier", "normal");
      doc.text(`${lastConf}`, MARGIN + CONTENT_W - 20, y + 4);
      if (delta !== 0) {
        setColor(doc, delta > 0 ? POSITIVE : NEGATIVE);
        doc.setFontSize(8);
        doc.text(delta > 0 ? `+${delta}` : `${delta}`, MARGIN + CONTENT_W - 8, y + 4);
      }

      y += 10;
    });

    // Legend
    y += 6;
    doc.setFillColor(...hexToRgb(ACCENT));
    doc.circle(MARGIN + 2, y, 1.5, "F");
    setColor(doc, TEXT_TERTIARY);
    doc.setFontSize(7);
    doc.text("Changed mind", MARGIN + 6, y + 1);

    doc.setFillColor(...hexToRgb(POSITIVE));
    doc.circle(MARGIN + 38, y, 1.5, "F");
    doc.text("Positive", MARGIN + 42, y + 1);

    doc.setFillColor(...hexToRgb(NEGATIVE));
    doc.circle(MARGIN + 62, y, 1.5, "F");
    doc.text("Negative", MARGIN + 66, y + 1);
  } else {
    setColor(doc, TEXT_TERTIARY);
    doc.setFontSize(10);
    doc.text("Evolution data not available.", MARGIN, y + 10);
  }

  footer(doc, 4, totalPages);

  // ═══ PAGE 5: DISSENT NOTES ═══
  doc.addPage();
  drawBg(doc);
  y = sectionLabel(doc, "Dissent Notes", 25);

  const dissents = verdict?.dissents || [];
  if (dissents.length > 0) {
    drawCard(doc, MARGIN, y, CONTENT_W, Math.min(dissents.length * 20 + 10, PAGE_H - y - 30));
    y += 8;
    dissents.forEach((d: any, i: number) => {
      if (y > PAGE_H - 30) {
        footer(doc, 5, totalPages);
        doc.addPage();
        drawBg(doc);
        y = 25;
      }

      if (i > 0) {
        doc.setDrawColor(...hexToRgb(BORDER));
        doc.setLineWidth(0.2);
        doc.line(MARGIN + 8, y - 2, MARGIN + CONTENT_W - 8, y - 2);
      }

      const agentName = typeof d.agent === "string" ? d.agent : "Agent";
      setColor(doc, getAgentColor(agentName));
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(agentName, MARGIN + 10, y + 2);

      if (d.note) {
        setColor(doc, TEXT_SECONDARY);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        const noteLines = wrapText(doc, typeof d.note === "string" ? d.note : String(d.note), CONTENT_W - 20);
        doc.text(noteLines.slice(0, 3), MARGIN + 10, y + 8);
        y += 8 + noteLines.slice(0, 3).length * 4;
      }
      y += 6;
    });
  } else {
    setColor(doc, TEXT_TERTIARY);
    doc.setFontSize(10);
    doc.text("No dissenting opinions recorded.", MARGIN, y + 10);
  }

  footer(doc, 5, totalPages);

  // ═══ PAGE 6: EMERGENT PATTERNS ═══
  doc.addPage();
  drawBg(doc);
  y = sectionLabel(doc, "Emergent Patterns", 25);

  const PATTERN_COLORS: Record<string, string> = {
    consensus: POSITIVE,
    emerging_risk: NEGATIVE,
    blind_spot: "#F59E0B",
    opportunity: "#3B82F6",
    tension: "#B8860B",
  };

  const patterns = verdict?.patterns || [];
  if (patterns.length > 0) {
    patterns.forEach((p: any) => {
      if (y > PAGE_H - 40) {
        footer(doc, 6, totalPages);
        doc.addPage();
        drawBg(doc);
        y = 25;
      }
      const pColor = PATTERN_COLORS[p.type] || TEXT_TERTIARY;
      drawCard(doc, MARGIN, y, CONTENT_W, 24);

      // Type dot
      doc.setFillColor(...hexToRgb(pColor));
      doc.circle(MARGIN + 8, y + 7, 1.5, "F");

      // Title
      setColor(doc, TEXT_PRIMARY);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(typeof p.title === "string" ? p.title : String(p.title ?? "Pattern"), MARGIN + 14, y + 8);

      // Type label
      setColor(doc, pColor);
      doc.setFontSize(7);
      doc.setFont("courier", "normal");
      doc.text((p.type || "").toUpperCase().replace(/_/g, " "), MARGIN + CONTENT_W - 40, y + 8);

      // Description
      if (p.description) {
        setColor(doc, TEXT_SECONDARY);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        const descLines = wrapText(doc, typeof p.description === "string" ? p.description : String(p.description), CONTENT_W - 20);
        doc.text(descLines.slice(0, 2), MARGIN + 14, y + 14);
      }

      // Agents involved
      if (p.agents_involved && Array.isArray(p.agents_involved) && p.agents_involved.length > 0) {
        setColor(doc, TEXT_TERTIARY);
        doc.setFontSize(7);
        doc.setFont("courier", "normal");
        doc.text(p.agents_involved.map((a: any) => typeof a === "string" ? a : String(a)).join(" · "), MARGIN + 14, y + 21);
      }

      y += 28;
    });
  } else {
    setColor(doc, TEXT_TERTIARY);
    doc.setFontSize(10);
    doc.text("No emergent patterns detected.", MARGIN, y + 10);
  }

  footer(doc, 6, totalPages);

  // Save
  const dateSlug = new Date().toISOString().slice(0, 10);
  doc.save(`signux-simulation-${dateSlug}.pdf`);
}
