import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          0: 'var(--surface-0)',
          1: 'var(--surface-1)',
          2: 'var(--surface-2)',
          3: 'var(--surface-3)',
          raised: 'var(--surface-raised)',
          overlay: 'var(--surface-overlay)',
        },
        /** BUILD PLAN §2.1 — sidebar surface (alias of --surface-1; themeable) */
        sidebar: 'var(--sidebar-bg)',
        txt: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          disabled: 'var(--text-disabled)',
          inverse: 'var(--text-inverse)',
          'on-accent': 'var(--text-on-accent)',
        },
        icon: {
          primary: 'var(--icon-primary)',
          secondary: 'var(--icon-secondary)',
          disabled: 'var(--icon-disabled)',
          active: 'var(--icon-active)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          active: 'var(--accent-active)',
          light: 'var(--accent-light)',
          muted: 'var(--accent-muted)',
          glow: 'var(--accent-glow)',
          subtle: 'var(--accent-subtle)',
          ring: 'var(--accent-ring)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          strong: 'var(--border-strong)',
          accent: 'var(--border-accent)',
        },
        verdict: {
          proceed: 'var(--verdict-proceed)',
          delay: 'var(--verdict-delay)',
          abandon: 'var(--verdict-abandon)',
          'proceed-muted': 'var(--verdict-proceed-muted)',
          'delay-muted': 'var(--verdict-delay-muted)',
          'abandon-muted': 'var(--verdict-abandon-muted)',
        },
        grade: { a: 'var(--grade-a)', b: 'var(--grade-b)', c: 'var(--grade-c)', d: 'var(--grade-d)', f: 'var(--grade-f)' },
        category: {
          investment: 'var(--cat-investment)',
          relationships: 'var(--cat-relationships)',
          career: 'var(--cat-career)',
          business: 'var(--cat-business)',
          health: 'var(--cat-health)',
          life: 'var(--cat-life)',
        },
        entity: {
          dormant: 'var(--entity-dormant)',
          active: 'var(--entity-active)',
          engaged: 'var(--entity-engaged)',
          maximum: 'var(--entity-maximum)',
          bioluminescent: 'var(--entity-bioluminescent)',
          neural: 'var(--entity-neural)',
          void: 'var(--entity-void)',
        },
        confidence: { high: 'var(--confidence-high)', medium: 'var(--confidence-medium)', low: 'var(--confidence-low)', contested: 'var(--confidence-contested)' },
        tier: { free: 'var(--tier-free)', pro: 'var(--tier-pro)', max: 'var(--tier-max)', kraken: 'var(--tier-kraken)' },
        'focus-ring': 'var(--focus-ring-color)',
        state: {
          success: 'var(--state-success)',
          'success-muted': 'var(--state-success-muted)',
          warning: 'var(--state-warning)',
          'warning-muted': 'var(--state-warning-muted)',
          error: 'var(--state-error)',
          'error-muted': 'var(--state-error-muted)',
          info: 'var(--state-info)',
          'info-muted': 'var(--state-info-muted)',
        },
        /** BUILD PLAN §2.1 */
        engine: {
          simulate: 'var(--engine-simulate)',
          build: 'var(--engine-build)',
          grow: 'var(--engine-grow)',
          hire: 'var(--engine-hire)',
          protect: 'var(--engine-protect)',
          compete: 'var(--engine-compete)',
        },
        role: {
          'base-rate': 'var(--agent-base-rate)',
          'unit-econ': 'var(--agent-unit-econ)',
          demand: 'var(--agent-demand)',
          competitive: 'var(--agent-competitive)',
          regulatory: 'var(--agent-regulatory)',
          execution: 'var(--agent-execution)',
          capital: 'var(--agent-capital)',
          scenario: 'var(--agent-scenario)',
          intervention: 'var(--agent-intervention)',
          chair: 'var(--agent-chair)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        micro: [
          'var(--text-micro-size)',
          { lineHeight: 'var(--text-micro-leading)', fontWeight: '400' },
        ],
        'page-title': [
          'var(--text-page-title-size)',
          {
            lineHeight: 'var(--text-page-title-leading)',
            letterSpacing: 'var(--text-page-title-tracking)',
            fontWeight: '300',
          },
        ],
        section: [
          'var(--text-section-size)',
          {
            lineHeight: 'var(--text-section-leading)',
            letterSpacing: 'var(--text-section-tracking)',
            fontWeight: '500',
          },
        ],
        'card-title': [
          'var(--text-card-title-size)',
          {
            lineHeight: 'var(--text-card-title-leading)',
            letterSpacing: 'var(--text-card-title-tracking)',
            fontWeight: '500',
          },
        ],
        'display-lg': [
          'var(--text-display-lg-size)',
          {
            lineHeight: 'var(--text-display-lg-leading)',
            letterSpacing: 'var(--text-display-lg-tracking)',
            fontWeight: '500',
          },
        ],
        meta: [
          'var(--text-meta-size)',
          { lineHeight: 'var(--text-meta-leading)', fontWeight: '400' },
        ],
        'xs': ['12px', { lineHeight: '1.5', letterSpacing: '0.005em' }],
        'sm': ['13px', { lineHeight: '1.55' }],
        'base': [
          'var(--text-body-size)',
          { lineHeight: 'var(--text-body-leading)', fontWeight: '400' },
        ],
        'md': ['15px', { lineHeight: '1.5', letterSpacing: '-0.005em' }],
        'lg': ['17px', { lineHeight: '1.45', letterSpacing: '-0.01em' }],
        'xl': ['20px', { lineHeight: '1.4', letterSpacing: '-0.015em' }],
        '2xl': ['24px', { lineHeight: '1.35', letterSpacing: '-0.02em' }],
        '3xl': ['28px', { lineHeight: '1.3', letterSpacing: '-0.025em' }],
        '4xl': ['36px', { lineHeight: '1.2', letterSpacing: '-0.03em' }],
        '5xl': ['48px', { lineHeight: '1.15', letterSpacing: '-0.035em' }],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
        full: '9999px',
        'radius-xs': 'var(--radius-xs)',
        'radius-sm': 'var(--radius-sm)',
        'radius-md': 'var(--radius-md)',
        'radius-lg': 'var(--radius-lg)',
        'radius-xl': 'var(--radius-xl)',
        'radius-2xl': 'var(--radius-2xl)',
        'radius-3xl': 'var(--radius-3xl)',
        'radius-full': 'var(--radius-full)',
        pill: 'var(--radius-pill)',
      },
      backgroundImage: {
        canvas: 'var(--canvas-gradient)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)', sm: 'var(--shadow-sm)', md: 'var(--shadow-md)', lg: 'var(--shadow-lg)', xl: 'var(--shadow-xl)',
        entity: 'var(--shadow-entity)', 'entity-glow': 'var(--shadow-entity-glow)', accent: 'var(--shadow-accent)',
        premium: 'var(--shadow-premium)',
        floating: 'var(--shadow-floating)',
        'accent-ring': 'var(--shadow-accent-ring)',
        'depth-sm': 'var(--shadow-depth-sm)',
        'depth-md': 'var(--shadow-depth-md)',
        'depth-lg': 'var(--shadow-depth-lg)',
        'verdict-proceed': '0 0 20px var(--verdict-proceed-muted)',
        'verdict-delay': '0 0 20px var(--verdict-delay-muted)',
        'verdict-abandon': '0 0 20px var(--verdict-abandon-muted)',
      },
      spacing: {
        'octx-1': 'var(--space-1)',
        'octx-2': 'var(--space-2)',
        'octx-3': 'var(--space-3)',
        'octx-4': 'var(--space-4)',
        'octx-5': 'var(--space-5)',
        'octx-6': 'var(--space-6)',
        'octx-8': 'var(--space-8)',
        'octx-10': 'var(--space-10)',
        'octx-12': 'var(--space-12)',
        'octx-16': 'var(--space-16)',
        'octx-24': 'var(--space-24)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-medium)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slow)',
        reveal: 'var(--duration-reveal)',
        entity: '500ms',
        takeover: '800ms',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        spring: 'var(--ease-spring)',
        entity: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      keyframes: {
        breathe: { '0%, 100%': { transform: 'scale(1)', opacity: '0.6' }, '50%': { transform: 'scale(1.03)', opacity: '1' } },
        'pulse-accent': { '0%, 100%': { boxShadow: '0 0 0 0 var(--accent-glow)' }, '50%': { boxShadow: '0 0 20px 8px var(--accent-glow)' } },
        'pulse-entity': { '0%, 100%': { boxShadow: '0 0 0 0 var(--entity-dormant)' }, '50%': { boxShadow: '0 0 40px 16px var(--entity-active)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'slide-in-right': { '0%': { transform: 'translateX(100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        'slide-in-left': { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(0)' } },
        'slide-in-up': { '0%': { transform: 'translateY(20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'scale-in': { '0%': { transform: 'scale(0.95)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        float: { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-6px)' } },
        'neural-flow': { '0%': { strokeDashoffset: '100' }, '100%': { strokeDashoffset: '0' } },
      },
      animation: {
        breathe: 'breathe 4s ease-in-out infinite',
        'breathe-fast': 'breathe 2s ease-in-out infinite',
        'pulse-accent': 'pulse-accent 2s ease-in-out infinite',
        'pulse-entity': 'pulse-entity 3s ease-in-out infinite',
        shimmer: 'shimmer 2s linear infinite',
        'slide-in-right': 'slide-in-right 0.2s ease-out',
        'slide-in-left': 'slide-in-left 0.25s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-up': 'slide-in-up 0.3s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
        float: 'float 3s ease-in-out infinite',
        'neural-flow': 'neural-flow 1.5s linear infinite',
      },
      width: { 'sidebar-collapsed': 'var(--sidebar-width-collapsed)', 'sidebar-expanded': 'var(--sidebar-width-expanded)', 'chat-max': 'var(--chat-max-width)' },
      maxWidth: {
        chat: 'var(--chat-max-width)',
        landing: 'var(--container-page)',
        narrow: '600px',
        'container-narrow': 'var(--container-narrow)',
        'container-page': 'var(--container-page)',
        reading: 'var(--container-reading)',
      },
      zIndex: { sidebar: '30', header: '40', dropdown: '50', modal: '60', toast: '70', tooltip: '80', command: '90', entity: '100', takeover: '110' },
    },
  },
  plugins: [],
};

export default config;
