const id: Record<string, string> = {
  "onboarding.welcome": "Selamat datang di Signux", "onboarding.subtitle": "Inteligensi operasional untuk operator global", "onboarding.email": "Alamat email", "onboarding.name": "Nama Anda", "onboarding.country": "Negara domisili pajak", "onboarding.language": "Bahasa pilihan", "onboarding.operations": "Apa yang Anda jalankan?", "onboarding.operations.import_export": "Impor/Ekspor", "onboarding.operations.offshore": "Offshore/Holding", "onboarding.operations.crypto": "Kripto", "onboarding.operations.digital_services": "Layanan Digital", "onboarding.operations.ecommerce": "E-commerce", "onboarding.operations.investments": "Investasi", "onboarding.operations.other": "Lainnya", "onboarding.start": "Mulai", "onboarding.terms": "Dengan melanjutkan, Anda menyetujui Ketentuan Layanan kami", "onboarding.country_placeholder": "Mis. Brasil, AS, Korea Selatan", "onboarding.choose_language": "Pilih bahasa Anda", "onboarding.search_language": "Cari bahasa...", "onboarding.loading_language": "Menyiapkan bahasa Anda...",
  "sidebar.chat": "Obrolan", "sidebar.simulate": "Simulasi", "sidebar.new_chat": "Percakapan baru", "sidebar.new_simulation": "Simulasi baru", "sidebar.history": "Riwayat", "sidebar.settings": "Pengaturan", "sidebar.mode_chat": "Obrolan", "sidebar.mode_simulate": "Simulasi", "sidebar.mode_intel": "Intelijen",
  "chat.greeting_morning": "Selamat pagi, {name}", "chat.greeting_afternoon": "Selamat siang, {name}", "chat.greeting_evening": "Selamat malam, {name}",
  "chat.welcome": "Halo, {name}.", "chat.welcome_subtitle": "Apa yang perlu Anda selesaikan hari ini?", "chat.placeholder": "Bagaimana Signux dapat membantu Anda hari ini?", "chat.send": "Kirim", "chat.copy": "Salin", "chat.copied": "Disalin", "chat.retry": "Coba lagi", "chat.good": "Membantu", "chat.bad": "Tidak membantu", "chat.export": "Ekspor percakapan", "chat.connection_error": "Kesalahan koneksi. Coba lagi.", "chat.enter_send": "Enter untuk mengirim, Shift+Enter untuk baris baru", "chat.searching": "Mencari informasi terkini...",
  "suggestion.1": "Mendirikan perusahaan di HK", "suggestion.2": "Rencana impor dari Tiongkok", "suggestion.3": "Lindungi aset kripto saya", "suggestion.4": "Briefing geopolitik hari ini",
  "sim.title": "Mesin Simulasi", "sim.subtitle": "Jelaskan skenario bisnis. Signux membuat agen khusus, mensimulasikan operasi, dan menyampaikan laporan lengkap.", "sim.placeholder": "Mis.: Saya ingin mengimpor 5.000 headphone bluetooth dari Shenzhen ke S\u00e3o Paulo. Anggaran $15.000. Belum pernah mengimpor.", "sim.examples_title": "Contoh skenario", "sim.start": "Mulai Simulasi", "sim.starting": "Memulai...", "sim.running": "Simulasi berjalan", "sim.running_subtitle": "Beberapa agen menganalisis skenario Anda...", "sim.result_title": "Hasil Simulasi", "sim.new_simulation": "Simulasi baru", "sim.export": "Ekspor", "sim.tab_report": "Laporan", "sim.tab_simulation": "Simulasi", "sim.tab_graph": "Grafik", "sim.specialists": "Spesialis", "sim.rounds": "Putaran", "sim.interactions": "Interaksi", "sim.type": "Tipe", "sim.agents_in_sim": "Agen dalam simulasi", "sim.entities": "Entitas", "sim.relationships": "Hubungan", "sim.key_variables": "Variabel kunci", "sim.critical_questions": "Pertanyaan kritis", "sim.try_again": "Coba lagi", "sim.ecosystem_title": "Simulasi Ekosistem", "sim.ecosystem_subtitle": "15+ agen spesialis mensimulasikan seluruh operasi Anda", "sim.agent_progress": "Agen {current} dari {total}", "sim.filter_all": "Semua", "sim.consensus": "Konsensus & Perbedaan Pendapat",
  "sim.category.supply": "Pasokan", "sim.category.logistics": "Logistik", "sim.category.finance": "Keuangan", "sim.category.regulatory": "Regulasi", "sim.category.market": "Pasar", "sim.category.legal": "Hukum", "sim.category.cultural": "Budaya", "sim.category.operations": "Operasi",
  "sim.example.1": "Impor 3.000 smartwatch dari Guangzhou ke Brasil melalui FOB", "sim.example.2": "Membuka holding di Hong Kong sambil tinggal di Brasil, volume $20K/bulan", "sim.example.3": "Ekspor kopi spesialti Brasil ke distributor di Tiongkok",
  "stage.intelligence": "Mengumpulkan intelijen waktu nyata", "stage.0": "Mengekstrak entitas dan hubungan", "stage.1": "Membuat agen khusus", "stage.2": "Menjalankan simulasi multi-agen", "stage.3": "Agen mendiskusikan skenario", "stage.4": "Menyusun laporan akhir",
  "sidebar.history.1": "Pendaftaran perusahaan di HK", "sidebar.history.2": "Rencana impor Tiongkok\u2192ID", "sidebar.history.3": "Tinjauan Kripto OPSEC", "sidebar.history.4": "Struktur pajak Dubai", "sidebar.history.5": "Analisis rantai pasokan",

  // SETTINGS
  "settings.title": "Pengaturan", "settings.general": "Umum", "settings.personalization": "Personalisasi", "settings.account": "Akun", "settings.language": "Bahasa", "settings.theme": "Tema", "settings.theme_auto": "Otomatis", "settings.theme_light": "Terang", "settings.theme_dark": "Gelap", "settings.web_search": "Pencarian web", "settings.web_search_desc": "Izinkan Signux mencari informasi terkini di web", "settings.about_you": "Tentang Anda", "settings.about_you_placeholder": "Ceritakan tentang diri Anda agar Signux dapat mempersonalisasi respons. Mis.: Saya pengusaha Brasil yang mengimpor elektronik dari Tiongkok, berdomisili di Seoul.", "settings.custom_instructions": "Instruksi khusus", "settings.custom_instructions_placeholder": "Mis.: Selalu jawab dalam bahasa Indonesia. Berikan rincian biaya dalam USD dan IDR. Langsung ke inti dan lewati peringatan umum.", "settings.memory": "Memori", "settings.memory_desc": "Izinkan Signux mengingat informasi dari percakapan", "settings.reference_history": "Referensi riwayat obrolan", "settings.reference_history_desc": "Gunakan percakapan sebelumnya sebagai konteks", "settings.name": "Nama", "settings.email": "Email", "settings.plan": "Paket", "settings.plan_free": "Gratis", "settings.upgrade": "Tingkatkan", "settings.delete_account": "Hapus akun", "settings.delete_confirm": "Anda yakin?", "settings.delete_confirm_desc": "Tindakan ini tidak dapat dibatalkan. Semua data Anda akan dihapus secara permanen.", "settings.cancel": "Batal", "settings.delete": "Hapus", "settings.saved": "Pengaturan disimpan",
  // SIMULATION (additional)
  "sim.complete": "Simulasi Selesai", "sim.duration": "Durasi",

  "common.beta": "Beta", "common.online": "Daring", "common.loading": "Memuat...", "common.error": "Kesalahan", "common.close": "Tutup", "common.welcome_toast": "Selamat datang, {name}", "common.disclaimer": "Signux bisa membuat kesalahan. Verifikasi informasi penting.", "common.today": "Hari ini", "common.previous_7_days": "7 hari terakhir", "common.previous_30_days": "30 hari terakhir", "common.version": "v0.1 Beta",
  "intel.title": "Briefing Intelijen", "intel.subtitle": "Analisis waktu nyata dari peristiwa global yang memengaruhi operasi Anda", "intel.generate": "Buat Briefing Hari Ini", "intel.generating": "Memindai sumber global...", "intel.generated_at": "Dibuat pada", "intel.update": "Perbarui Briefing", "intel.ask": "Tanyakan tentang ini", "intel.focus": "Area fokus", "intel.risk.low": "Risiko Rendah", "intel.risk.medium": "Risiko Sedang", "intel.risk.high": "Risiko Tinggi", "intel.risk.critical": "Kritis", "intel.focus.geopolitics": "Geopolitik", "intel.focus.regulations": "Regulasi", "intel.focus.markets": "Pasar", "intel.focus.logistics": "Logistik", "intel.focus.crypto": "Kripto",
};

export default id;
