const th: Record<string, string> = {
  "onboarding.welcome": "มาตั้งค่าพื้นที่ทำงานของคุณกัน", "onboarding.subtitle": "ระบบอัจฉริยะเฉพาะตัวคุณ ภายในไม่ถึงนาที", "onboarding.email": "ที่อยู่อีเมล", "onboarding.name": "ชื่อของคุณ", "onboarding.country": "ประเทศที่พำนักภาษี", "onboarding.language": "ภาษาที่ต้องการ", "onboarding.operations": "คุณโฟกัสด้านไหน?", "onboarding.operations.import_export": "นำเข้า/ส่งออก", "onboarding.operations.offshore": "Offshore/Holding", "onboarding.operations.crypto": "คริปโต", "onboarding.operations.digital_services": "บริการดิจิทัล", "onboarding.operations.ecommerce": "อีคอมเมิร์ซ", "onboarding.operations.investments": "การลงทุน", "onboarding.operations.other": "อื่นๆ", "onboarding.start": "เข้าสู่ Signux", "onboarding.terms": "เมื่อดำเนินการต่อ ถือว่าคุณยอมรับข้อกำหนดการใช้บริการ", "onboarding.country_placeholder": "เช่น บราซิล, สหรัฐฯ, เกาหลีใต้", "onboarding.choose_language": "เลือกภาษาของคุณ", "onboarding.search_language": "ค้นหาภาษา...", "onboarding.loading_language": "กำลังเตรียมภาษาของคุณ...",
  "sidebar.chat": "แชท", "sidebar.simulate": "จำลอง", "sidebar.new_chat": "บทสนทนาใหม่", "sidebar.new_simulation": "การจำลองใหม่", "sidebar.history": "ประวัติ", "sidebar.settings": "การตั้งค่า", "sidebar.mode_chat": "แชท", "sidebar.mode_simulate": "จำลอง", "sidebar.mode_intel": "ข่าวกรอง",
  "chat.greeting_morning": "สวัสดีตอนเช้า, {name}", "chat.greeting_afternoon": "สวัสดีตอนบ่าย, {name}", "chat.greeting_evening": "สวัสดีตอนเย็น, {name}",
  "chat.welcome": "สวัสดี, {name}.", "chat.welcome_subtitle": "วันนี้คุณต้องการแก้ไขอะไร?", "chat.placeholder": "ถามเกี่ยวกับโครงสร้าง, นำเข้า, คริปโต, ตลาด...", "chat.send": "ส่ง", "chat.copy": "คัดลอก", "chat.copied": "คัดลอกแล้ว", "chat.retry": "ลองใหม่", "chat.good": "มีประโยชน์", "chat.bad": "ไม่มีประโยชน์", "chat.export": "ส่งออกบทสนทนา", "chat.connection_error": "ไม่สามารถเชื่อมต่อได้ ตรวจสอบอินเทอร์เน็ตแล้วลองอีกครั้ง", "chat.enter_send": "Enter ส่ง, Shift+Enter ขึ้นบรรทัดใหม่", "chat.searching": "กำลังค้นหาข้อมูลล่าสุด...",
  "suggestion.1": "โครงสร้าง offshore ที่ดีที่สุดสำหรับ e-commerce", "suggestion.2": "คำนวณต้นทุนนำเข้า: จีนไปบราซิล", "suggestion.3": "ตรวจสอบระบบรักษาความปลอดภัยคริปโตของฉัน", "suggestion.4": "ข่าววันนี้ส่งผลต่อธุรกิจของฉันอย่างไร",
  "sim.title": "จำลอง", "sim.subtitle": "อธิบายการดำเนินงาน Signux จะส่งนักวิเคราะห์เฉพาะทาง จำลองทุกตัวแปร และส่งมอบบทสรุปฉบับสมบูรณ์", "sim.placeholder": "คุณต้องการทดสอบการดำเนินงานใด?",
  "sim.examples_title": "ตัวอย่างสถานการณ์", "sim.start": "เริ่มจำลอง", "sim.starting": "กำลังเริ่ม...", "sim.running": "กำลังจำลอง...", "sim.running_subtitle": "15 ผู้เชี่ยวชาญกำลังวิเคราะห์การดำเนินงานของคุณ...", "sim.result_title": "การวิเคราะห์เสร็จสิ้น", "sim.new_simulation": "การจำลองใหม่", "sim.export": "ส่งออก", "sim.tab_report": "รายงาน", "sim.tab_simulation": "การจำลอง", "sim.tab_graph": "กราฟ", "sim.specialists": "ผู้เชี่ยวชาญ", "sim.rounds": "รอบ", "sim.interactions": "ปฏิสัมพันธ์", "sim.type": "ประเภท", "sim.agents_in_sim": "ผู้เชี่ยวชาญในการจำลอง", "sim.entities": "สิ่งที่เกี่ยวข้อง", "sim.relationships": "ความสัมพันธ์", "sim.key_variables": "ตัวแปรสำคัญ", "sim.critical_questions": "คำถามสำคัญ", "sim.try_again": "ลองใหม่", "sim.ecosystem_title": "จำลองการดำเนินงาน", "sim.ecosystem_subtitle": "ผู้เชี่ยวชาญ 15 คนวิเคราะห์การดำเนินงานของคุณ", "sim.agent_progress": "ผู้เชี่ยวชาญ {current} จาก {total}", "sim.filter_all": "ทั้งหมด", "sim.consensus": "ฉันทามติและความเห็นต่าง",
  "sim.category.supply": "อุปทาน", "sim.category.logistics": "โลจิสติกส์", "sim.category.finance": "การเงิน", "sim.category.regulatory": "กฎระเบียบ", "sim.category.market": "ตลาด", "sim.category.legal": "กฎหมาย", "sim.category.cultural": "วัฒนธรรม", "sim.category.operations": "การดำเนินงาน",
  "sim.example.1": "นำเข้าสมาร์ทวอทช์ 3,000 เรือนจากกวางโจวไปบราซิลแบบ FOB", "sim.example.2": "เปิดโฮลดิ้งในฮ่องกงขณะอาศัยในบราซิล ปริมาณ $20K/เดือน", "sim.example.3": "ส่งออกกาแฟพิเศษบราซิลไปยังผู้จัดจำหน่ายในจีน",
  "stage.intelligence": "รวบรวมข่าวกรองแบบเรียลไทม์", "stage.0": "จับคู่เอนทิตีและความสัมพันธ์", "stage.1": "ส่งผู้เชี่ยวชาญเฉพาะทางลงสนาม", "stage.2": "รันการจำลองหลายตัวแทน", "stage.3": "ผู้เชี่ยวชาญถกเถียงสถานการณ์", "stage.4": "รวบรวมรายงานสุดท้าย",
  "sidebar.history.1": "จดทะเบียนบริษัทใน HK", "sidebar.history.2": "แผนนำเข้าจีน→TH", "sidebar.history.3": "ตรวจสอบคริปโต OPSEC", "sidebar.history.4": "โครงสร้างภาษีดูไบ", "sidebar.history.5": "วิเคราะห์ห่วงโซ่อุปทาน",

  // SETTINGS
  "settings.title": "การตั้งค่า", "settings.general": "ทั่วไป", "settings.personalization": "ปรับแต่ง", "settings.account": "บัญชี", "settings.language": "ภาษา", "settings.theme": "ธีม", "settings.theme_auto": "อัตโนมัติ", "settings.theme_light": "สว่าง", "settings.theme_dark": "มืด", "settings.web_search": "ค้นหาเว็บ", "settings.web_search_desc": "อนุญาตให้ Signux ค้นหาข้อมูลล่าสุดบนเว็บ", "settings.about_you": "บริบทของคุณ", "settings.about_you_subtitle": "ช่วยให้ Signux ตอบคำถามได้ดียิ่งขึ้น", "settings.about_you_placeholder": "บอก Signux เกี่ยวกับตัวคุณเพื่อปรับแต่งคำตอบ เช่น ผมเป็นผู้ประกอบการชาวบราซิลนำเข้าอิเล็กทรอนิกส์จากจีน อาศัยอยู่ในโซล", "settings.custom_instructions": "การตั้งค่าการตอบกลับ", "settings.custom_instructions_subtitle": "Signux ควรสื่อสารกับคุณอย่างไร?", "settings.custom_instructions_placeholder": "เช่น ตอบเป็นภาษาไทยเสมอ แสดงรายละเอียดต้นทุนเป็น USD และ THB พูดตรงๆ และข้ามคำเตือนทั่วไป", "settings.memory": "ความจำ", "settings.memory_desc": "อนุญาตให้ Signux จดจำข้อมูลจากการสนทนา", "settings.reference_history": "อ้างอิงประวัติแชท", "settings.reference_history_desc": "ใช้การสนทนาก่อนหน้าเป็นบริบท", "settings.name": "ชื่อ", "settings.email": "อีเมล", "settings.plan": "แพ็กเกจ", "settings.plan_free": "ฟรี", "settings.upgrade": "อัปเกรด", "settings.delete_account": "ลบบัญชี", "settings.delete_confirm": "คุณแน่ใจหรือไม่?", "settings.delete_confirm_desc": "การดำเนินการนี้ไม่สามารถย้อนกลับได้ ข้อมูลทั้งหมดของคุณจะถูกลบอย่างถาวร", "settings.cancel": "ยกเลิก", "settings.delete": "ลบ", "settings.saved": "บันทึกการตั้งค่าแล้ว", "settings.replay_tutorial": "เล่นบทแนะนำอีกครั้ง",
  // SIMULATION (additional)
  "sim.complete": "การวิเคราะห์เสร็จสิ้น", "sim.duration": "ระยะเวลา",

  "common.beta": "เบต้า", "common.online": "ออนไลน์", "common.loading": "กำลังโหลด...", "common.error": "เกิดข้อผิดพลาด", "common.close": "ปิด", "common.welcome_toast": "ยินดีต้อนรับ, {name}", "common.disclaimer": "กรุณาตรวจสอบการตัดสินใจสำคัญกับผู้เชี่ยวชาญที่มีคุณสมบัติเสมอ", "common.you": "คุณ", "common.today": "วันนี้", "common.previous_7_days": "7 วันที่ผ่านมา", "common.previous_30_days": "30 วันที่ผ่านมา", "common.version": "v0.1 เบต้า",
  "intel.title": "ข่าวกรองวันนี้", "intel.subtitle": "การวิเคราะห์เหตุการณ์โลกที่ส่งผลต่อการดำเนินงานของคุณแบบเรียลไทม์", "intel.generate": "รับสรุปข่าววันนี้", "intel.generating": "กำลังวิเคราะห์เหตุการณ์ทั่วโลก...", "intel.generated_at": "สร้างเมื่อ", "intel.update": "อัปเดตสรุปข่าว", "intel.ask": "ถามเกี่ยวกับเรื่องนี้", "intel.focus": "พื้นที่โฟกัส", "intel.risk.low": "ความเสี่ยงต่ำ", "intel.risk.medium": "ความเสี่ยงปานกลาง", "intel.risk.high": "ความเสี่ยงสูง", "intel.risk.critical": "วิกฤต", "intel.focus.geopolitics": "ภูมิรัฐศาสตร์", "intel.focus.regulations": "กฎระเบียบ", "intel.focus.markets": "ตลาด", "intel.focus.logistics": "โลจิสติกส์", "intel.focus.crypto": "คริปโต",

  // TOUR
  "tour.step1.title": "ถามได้ทุกเรื่อง", "tour.step1.desc": "โครงสร้าง, นำเข้า, คริปโต, ตลาด, ภูมิรัฐศาสตร์ — Signux ครอบคลุม 20+ สาขา แค่พิมพ์คำถามของคุณ", "tour.step2.title": "พื้นที่ทำงาน", "tour.step2.desc": "บทสนทนา, โหมด, และการตั้งค่า — ทุกอย่างอยู่ในแถบด้านข้าง", "tour.step3.title": "เริ่มจำลอง", "tour.step3.desc": "อธิบายการดำเนินงาน แล้วผู้เชี่ยวชาญ 15 คนจะจำลองครบทุกขั้นตอนพร้อมคำตัดสิน GO/NO-GO", "tour.step3.recommended": "แนะนำ", "tour.step4.title": "ข่าวกรองรายวัน", "tour.step4.desc": "รับสรุปเหตุการณ์ทั่วโลกแบบเรียลไทม์ — การเปลี่ยนแปลงกฎระเบียบ, ความผันผวนของตลาด, และความเสี่ยงด้านภูมิรัฐศาสตร์", "tour.step5.title": "ปรับให้เป็นของคุณ", "tour.step5.desc": "ตั้งค่าภาษา, อธิบายธุรกิจของคุณ, และกำหนดวิธีที่ Signux ตอบกลับ", "tour.skip": "ข้าม", "tour.next": "ถัดไป", "tour.finish": "เริ่มกันเลย", "tour.step_of": "{current} จาก {total}",
};

export default th;
